name: Build-Iso
on:
  schedule:
    - cron: "00 06 1 * *" # build at 06:00 UTC on the first of the month 
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      
  pull_request:
  workflow_dispatch: # allow manually triggering builds

jobs:
  build_push:
    name: Build Custom Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here 
          - recipe.yml
          
    steps:
      - name: Build ISOs
        uses: jasonn3/build-container-installer@v1.2.1
        id: build
        with:
          arch: x86_64
          image_name: edublue
          image_repo: ghcr.io/projm-dev-team
          variant: 'Kinoite'
          version: '40'
          secure_boot_key_url: 'https://github.com/ublue-os/akmods/raw/main/certs/public_key.der'
          enrollment_password: 'ublue-os'
          iso_name: edublue.iso

      - name: Upload ISOs and Checksum to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: edublue
          path: ${{ steps.build.outputs.iso_path }}
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
